baseURL = "https://lire-readtheroom.github.io/"
SectionPagesMenu = "main"
languageCode = "en-us"
googleAnalytics = ""
enableRobotsTXT = true
title = ""
theme = "ananke"

[pagination]
  pagerSize = 10

[languages]
[languages.en]
title = "READING THE ROOM SINCE 1996"
weight = 1
contentDir = "content/en"
# languageDirection = 'rtl' for Right-To-Left languages
[languages.pt]
title = "READING THE ROOM SINCE 1996"
weight = 2
contentDir = "content/pt"


[params]
  author = ""
  description = ""
  background_color_class = "bg-white"
  text_color_class = "text-black"
  mainSections = ["posts"]
  site_logo = "images/logo.png"  # path to your logo inside static/images/

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"
