baseURL = "https://lire-readtheroom.github.io/"
languageCode = "en-us"
title = "Lïre"
description = "Reading the Room"
theme = "ananke"
resourceDir = "../resources"

[params]
  author = ""
  description = "Reading the Room"
  background_color_class = "bg-black"
  text_color_class = "text-white"
  mainSections = ["posts"]
  site_logo = "images/wlogo.png"  
  recent_posts_number = 3

[pagination]
  pagerSize = 20

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4